-- Hyprland + Dank: simple keyboard-driven desktop.
hl.config({
    autogenerated = false,
    input = { kb_layout = "us", numlock_by_default = true, follow_mouse = 1, mouse_refocus = true, sensitivity = 0.0, accel_profile = "flat", force_no_accel = false },
    general = { gaps_in = 2, gaps_out = 4, border_size = 2, layout = "dwindle", resize_on_border = true },
    decoration = {
        rounding = 10, active_opacity = 1.0, inactive_opacity = 1.0,
        shadow = { enabled = true, range = 4, render_power = 2, color = "rgba(00000045)" },
        blur = { enabled = false },
    },
    animations = { enabled = true },
    dwindle = { preserve_split = true },
    misc = { disable_hyprland_logo = true, disable_splash_rendering = true, vrr = 0 },
})
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("MANGOHUD", "0")
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")
hl.env("TERMINAL", "alacritty")
hl.env("LANG", "en_US.UTF-8")
hl.env("LC_CTYPE", "en_US.UTF-8")
hl.env("LC_NUMERIC", "en_US.UTF-8")
hl.env("LC_TIME", "en_US.UTF-8")
hl.env("LC_COLLATE", "en_US.UTF-8")
hl.env("LC_MONETARY", "en_US.UTF-8")
hl.env("LC_MESSAGES", "en_US.UTF-8")
hl.env("LC_PAPER", "en_US.UTF-8")
hl.env("LC_NAME", "en_US.UTF-8")
hl.env("LC_ADDRESS", "en_US.UTF-8")
hl.env("LC_TELEPHONE", "en_US.UTF-8")
hl.env("LC_MEASUREMENT", "en_US.UTF-8")
hl.env("LC_IDENTIFICATION", "en_US.UTF-8")
hl.env("LANGUAGE", "en_US:en")
hl.on("hyprland.start", function()
    hl.exec_cmd("@HOME@/.config/hypr/start-session.sh")
end)
hl.on("hyprland.shutdown", function()
    hl.exec_cmd("@HOME@/.config/hypr/stop-session.sh")
end)
hl.animation({ leaf = "global", enabled = true, speed = 8, bezier = "default" })
hl.layer_rule({ match = { namespace = "^dms:.*" }, no_anim = true })
hl.layer_rule({ match = { namespace = "^(quickshell)$" }, no_anim = true })
require("dms.colors")
require("dms.layout")
hl.config({ general = { gaps_in = 2, gaps_out = 4 } })
require("dms.outputs")
require("dms.cursor")
require("dms.windowrules")
require("windowrules")
require("keybinds")
