#!/bin/sh
set -eu
case "${XDG_CURRENT_DESKTOP:-}" in *Hyprland*) ;; *) exit 0;; esac
export MANGOHUD=0
export QT_QPA_PLATFORM='wayland;xcb'
export ELECTRON_OZONE_PLATFORM_HINT=auto
export TERMINAL=alacritty
export XDG_SESSION_TYPE=wayland
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export LC_NUMERIC=en_US.UTF-8
export LC_TIME=en_US.UTF-8
export LC_COLLATE=en_US.UTF-8
export LC_MONETARY=en_US.UTF-8
export LC_MESSAGES=en_US.UTF-8
export LC_PAPER=en_US.UTF-8
export LC_NAME=en_US.UTF-8
export LC_ADDRESS=en_US.UTF-8
export LC_TELEPHONE=en_US.UTF-8
export LC_MEASUREMENT=en_US.UTF-8
export LC_IDENTIFICATION=en_US.UTF-8
export LANGUAGE=en_US:en
if uwsm check is-active compositor-only; then
    uwsm finalize HYPRLAND_INSTANCE_SIGNATURE XDG_CURRENT_DESKTOP XDG_SESSION_TYPE MANGOHUD QT_QPA_PLATFORM ELECTRON_OZONE_PLATFORM_HINT TERMINAL LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT LC_IDENTIFICATION LANGUAGE
else
    dbus-update-activation-environment --systemd WAYLAND_DISPLAY DISPLAY HYPRLAND_INSTANCE_SIGNATURE XDG_CURRENT_DESKTOP XDG_SESSION_TYPE MANGOHUD QT_QPA_PLATFORM ELECTRON_OZONE_PLATFORM_HINT TERMINAL LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT LC_IDENTIFICATION LANGUAGE
    systemctl --user start hyprland-dank-session.target
fi
systemctl --user start --no-block dank-hyprland.service udiskie-hyprland.service gsr-ui-hyprland.service
